#!/bin/bash

# TODO: we need to convert this wrapper to use a bin launcher
# including shotgun api to the shotgun python executable
shotgunApiPath="$( locres apps/shotgunDesktop/$UVER_SHOTGUNDESKTOP_VERSION )/bin/$USYS_OS/Resources/Python/tk-framework-desktopstartup/python/tk-core/python/tank_vendor"
ushotgun="$( locres libs/ushotgun/$UVER_USHOTGUN_VERSION )/lib/python$(majorver $UVER_UPYTHON_VERSION)/lib"
ingestor="$( locres apps/ingestor/$UVER_INGESTOR_VERSION )/python$(majorver $UVER_UPYTHON_VERSION)/lib"
export PYTHONPATH="$shotgunApiPath:$ushotgun:$ingestor:$PYTHONPATH"

# executing shotgun python
exec "$SHOTGUN_PYTHON_EXECUTABLE" "$@"
